runtime: java
env: flex
runtime_config:
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1
endpoints_api_service:
  name: sithivili.appspot.com
  rollout_strategy: managed